### ISSUE TITLE
Support for DEFAULT_ACCOUNT?

### ISSUE THREAD

**Issue by fab13n** [OCamlPro/liquidity#1]
I can't find a way to support the DEFAULT_ACCOUNT primitive, neither in the doc nor through a cursory look at the sources. Is it missing? For a legitimate reason?

**Comment by lefessan** [comment]
I updated Liquidity to the most recent version of Michelson, so this problem is fixed.

The language was not updated because there are big changes coming in Michelson, and it will change a lot the way calls between contracts are done.

**Comment by fab13n** [comment]
It would be nice to give a heads up about the envisioned and coming changes to the the community (including but not limited to Michelson evolutions), given that the governance should progressively be transferred to that community!
