### ISSUE TITLE
Serialization format for passing parameters at the command line

### ISSUE THREAD

**Issue by whaatt** [OCamlPro/liquidity#110]
The usage doc gives this example to test a contract: `./_obuild/liquidity/liquidity.asm --amount 5tz --run tests/others/demo.liq '""' 'Map ["", 0]'`

Is there anywhere where the format of parameter strings like `Map ["", 0]` is formally defined?

**Comment by mebsout** [comment]
Parameters to use on the command line are _constant_ values in the Liquidity syntax. The specification can be read there http://www.liquidity-lang.org/doc/reference/liquidity.html#constants-values.
