### ISSUE TITLE
any plans to use the Michelson type annotations?

### ISSUE THREAD

**Issue by martinpospech** [OCamlPro/liquidity#111]
Is there any plan to compile Liquidity types into Michelson types with the type annotations?

E.g. the names of individual variants in a variant type could be used as the annotations.

```
type something =
| A of unit
| B of unit

(pair (unit :A) (unit :B))
```

**Comment by mebsout** [comment]
Yes, we plan on using them but the harder part is recovering exact Liquidity types when decompiling.
Your example type would be compiled as 
```ocaml
(or (unit %A) (unit %B))
```
(The annotation `:` is for type aliases/names in Michelson, while `%` is for field names and constructor names.)
