### ISSUE TITLE
Missing argument types for liquidity functions (Contract.create, Account.create, Contract.set_delegate)

### ISSUE THREAD

**Issue by eddiew** [OCamlPro/liquidity#114]
I'm trying to write some contracts in liquidity and am having a lot of trouble figuring out what the types are for the arguments to these functions.

**Comment by mebsout** [comment]
We have update the documentation to make this clearer: http://www.liquidity-lang.org/doc/reference/liquidity.html#operations-on-contracts. Note that a future version will allow to use labelled arguments (in any order) for some of these functions (_e.g._ one will be able to write `Contract.create ~manager:tz1... ~delegate:None ~spendable:true ...`).
