### ISSUE TITLE
Type of primitive "Some" is not convertible with int

### ISSUE THREAD

**Issue by styts** [OCamlPro/liquidity#125]
Trying to examine the contract KT1WJ1tKARGLmEhrUyLyTUjXdBfaEQQjyvkZ from the mainnet via the web editor, getting the above error.
<img width="823" alt="screen shot 2018-09-29 at 18 49 21" src="https://user-images.githubusercontent.com/293400/46248356-94d44a80-c418-11e8-90ed-fd13813ee371.png">

**Comment by mebsout** [comment]
The web editor assumes that the contract at the address you entered is the same as the one in the liquidity editor on the left. So if the storage types are not compatible it will fail to translate its value back to Liquidity syntax when you click "Retrieve ...".
What you can do instead is to first decompile the contract to its Liquidity version, by using http://www.liquidity-lang.org/edit/?contract=KT1WJ1tKARGLmEhrUyLyTUjXdBfaEQQjyvkZ for instance.

**Comment by styts** [comment]
That solves it, thanks! Might want to show a nicer error, in case others run into it (or pre-load the contract if the storage type incompatibility is detected).

**Comment by mebsout** [comment]
Fixed in last version of try-liquidity on http://www.liquidity-lang.org/edit.
