### ISSUE TITLE
Is it possible to remove annotations in liquidity 0.4?

### ISSUE THREAD

**Issue by catsigma** [OCamlPro/liquidity#140]
When originating contracts, `tezos-node` will not only check the contract type matching, but also the annotations.

We will get `inconsistent_annotations` error when we try to deploy a contract like this:

```
              {
                "kind": "permanent",
                "id": "proto.002-PsYLVpVv.inconsistentAnnotations",
                "annot1": ":CallbackContract",
                "annot2": ":Token.TokenContract.CallbackContract"
              }
```

But they are actually the same type, just having different annotations.

**Comment by mebsout** [comment]
Ok, I will try to add back the --no-annot option. Can you send an example that shows this bug though?

**Comment by catsigma** [comment]
It's like this

If you has a liq named `a.liq` as this
```
contract type X = sig
  type storage
  val%entry main : unit -> _
end

contract Y = struct
  type storage = unit

  let%entry main (parameter : X.instance) storage =
    ([] : operation list), storage
end
```

Let's say you had originated the Y contact and get the contract address as `KT1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAaliq`


And another liq file named `b.liq` as this
```
contract Z = struct
  type storage = A.Y.instance

  let%entry main (parameter : unit) storage =
    ([] : operation list), storage
end
```




When you originate this contract with `KT1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAaliq` to init storage, you can get the error.



**===PS===**
There is another issue when compiling the b.liq file.
```
  parameter unit;
  storage (contract (contract :A.Y.X unit));    <-  error
  code { CDR @storage_slash_1 ; NIL operation ; PAIR };
```
