### ISSUE TITLE
Add support for not generating LAMBDA when using [@inline]

### ISSUE THREAD

**Issue by catsigma** [OCamlPro/liquidity#142]
In current version of liquidity, using `[@inline]` will still generate a lambda function everytime which can consume more gas than normal usage.

**Comment by catsigma** [comment]
Thanks for the example. Now I get the to inline function correctly in current version of Liquidity.

**Comment by mebsout** [comment]
Liquidity now inlines closures properly thanks to 9d0c404 and performs uncurrying automatically (the transformation from functions with multiple aguments to functions with a single tuple argument is performed automatically) thanks to #203.
