### ISSUE TITLE
Add support for entry parameter type reference for contract modules

### ISSUE THREAD

**Issue by catsigma** [OCamlPro/liquidity#145]
Like if we has a `a.liq`:
```
contract type X = sig
  type storage
  val%entry aa : unit -> _
  val%entry bb : nat * string -> _
end
```

We can use some instructions to refer the parameter type of `aa` or `bb`:

```
X.aa.parameter            <-           is unit type
X.bb.parameter            <-          is nat * string type
```

**Comment by lefessan** [comment]
There is now type inference in the `next` branch of Liquidity. It may remove the need for such automatically generated type aliases.
