### ISSUE TITLE
expected (address * nat), got address

### ISSUE THREAD

**Issue by gspeagle** [OCamlPro/liquidity#153]
Having a problem calling a contract on alphanet. Contract deploys just fine.  When  I try to call with two arguments,  even if they are same type, I am getting error I mentioned in subject line.

**Comment by lefessan** [comment]
If the contract is deployed, could you send us the KT1 ?

**Comment by gspeagle** [comment]
KT1RpPcMNJaDTcdX8a9g3su3qYHdJeAwwxSJ   (alphanet)

**Comment by mebsout** [comment]
Thank you. Which call are you trying to make? That is, which entry point and parameter are you passing? Also, are you using the tezos-client, the liquidity command line compiler, or the editor at liquidity-lang.org to make the call (or another wallet) ?

**Comment by mebsout** [comment]
Ok, I guess you want to call `transfer`.  For this you need to give a pair as a parameter, in Liquidity syntax that is `(tz1WWXeGFgtARRLPPzT2qcpeiQZ8oQb6rBZd, 99p)` where `tz1...` is the destination and `99p` is the amount you want to transfer (the suffix `p` is for natural numbers in Liquidity). Let us know if that (doesn't) work.

**Comment by gspeagle** [comment]
liquidity --tezos-node http://127.0.0.1:8732 --amount 1tz --fee 0tz --private-key xxxxx
others/token.liq --call KT1RpPcMNJaDTcdX8a9g3su3qYHdJeAwwxSJ transfer 'tz1XXpE5ZqqqZSACTG1bxbrH6SbuJ3VLQ8gs' , '99p'
Main contract Token
call_parameter:1.-1-1.-1: Error: Type error:  constant type mismatch, expected (address * nat), got key_hash

**Comment by gspeagle** [comment]
liquidity --tezos-node http://127.0.0.1:8732 --amount 1tz --fee 0tz --private-key xxxxxxx  others/token.liq --call KT1RpPcMNJaDTcdX8a9g3su3qYHdJeAwwxSJ transfer 'KT1B6dcifVHRZiUCrqncZiNjLAeCWaZVCZmf' , '99p'
Main contract Token
call_parameter:1.-1-1.-1: Error: Type error:  constant type mismatch, expected (address * nat), got address

**Comment by gspeagle** [comment]
This is what I have been running into.  This is with the "transfer".  However, it happens with any other parameter I am passing in other sections of the contract

**Comment by gspeagle** [comment]
I might be misunderstanding the how to call the parameters, but calls to to other contracts using this syntax is working.  I get a runtime error if use the following form "(tz1... , 99p)  with the parentheses included.  Could my issue be the runtime error  with the correct syntax for calling the contract?

**Comment by gspeagle** [comment]
Thanks,
