### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by mebsout** [OCamlPro/liquidity#16]

**Comment by shogochiai** [comment]
+1 for this.

I read https://github.com/OCamlPro/liquidity/blob/next/docs/liquidity.md and still haven't understand well about how `storage` type works and with method is on that. Especially `getter` `setter` behavior is not clear for me. If anyone share me some good to read, I can edit this repo's doc accordingly.

**Comment by mebsout** [comment]
Everything that is between `(* ... *)` are comments in Liquidity. This T was the name of a variable from a manually translated Michelson file so this is why the annotation was put there.

The type storage is this one (without comments), it is a tuple with 6 components:
```ocaml
type storage =  string *
                timestamp *
                (tez * tez) *
                (unit,unit) contract *
                (unit,unit) contract *
                (unit,unit) contract
```

**Comment by shogochiai** [comment]
Thanks @mebsout , I could get the missing link.

I'm willing to contribute to this repo by writing docs regarding this `storage` understanding.
Maybe my 1st pull-req would start from so poor one, but plz kindly feed me back and I may be able to make it enough good for this repo, finally.
