### ISSUE TITLE
Try-Liquidity settings: No nodes available for testing contracts

### ISSUE THREAD

**Issue by berndoostrum** [OCamlPro/liquidity#168]
![image](https://user-images.githubusercontent.com/12640891/50450591-f8591000-0954-11e9-99b4-239bf189387b.png)

None of the nodes are available for testing on the try-liquidity website.

**Comment by lefessan** [comment]
alphanet-node.tzscan.io should work now. But `node.tzscan.io` should be replaced by `mainnet-node.tzscan.io`
