### ISSUE TITLE
Can't install liquildity-----Could not extract archive!!!!!

### ISSUE THREAD

**Issue by purplecity** [OCamlPro/liquidity#169]
when install liquildity
make build-deps.

<img width="950" alt="tezos9" src="https://user-images.githubusercontent.com/38914615/51104091-0f867180-1820-11e9-8417-4c5ccc3d759f.png">

I have see  can't extract archive file is .tbz file such as cmdliner.  and .tar.gz is ok.

**Comment by fredcy** [comment]
Perhaps you're missing bzip2?

**Comment by lefessan** [comment]
This is an opam issue, not liquidity issue. We cannot fix it.
