### ISSUE TITLE
Better support for ReasonML syntax

### ISSUE THREAD

**Issue by maht0rz** [OCamlPro/liquidity#173]
Liquidity version: 0.5

Documentation specifies that we should be able to coerce `string` to `tez` as following:

```
("1.00" : tez)
```

However, this produces an error, e.g. when compared with `Current.amount()`

```
[%%version 0.4]
let minAmount (amount : tez) = ()
type storage = int
[%%init let init_storage = 0]
[%%entry
  let main (parameter : int) storage =
    let amount = ("1.00" : tez) in
    minAmount amount; ([], (storage + parameter))]
```

However, coercing `integer` to `nat` works as expected.

![image](https://user-images.githubusercontent.com/6826282/52310157-b8009f00-29a2-11e9-835d-7772d3d87328.png)

[Related stack exchange question](https://tezos.stackexchange.com/questions/258/how-can-a-string-be-coerced-into-tez-using-liquidity)

**Comment by mebsout** [comment]
You are right, the documentation is incorrect in this respect. This was removed some time ago. Constants have to be written as literals now (i.e. `1tz` or `1.00tz`).

**Comment by maht0rz** [comment]
Thanks for your answer

**Comment by lefessan** [comment]
If you want to try #175 , feedback welcome !

**Comment by lefessan** [comment]
ReasonML syntax is supported in `next`
