### ISSUE TITLE
assert failure

### ISSUE THREAD

**Issue by sacerdot** [OCamlPro/liquidity#176]
I get an assert false trying to make a call on alphanet
[cassonetto.txt](https://github.com/OCamlPro/liquidity/files/2847393/cassonetto.txt)

./liquidity.asm --amount 1tz --fee 0tz --private-key edsk3RfJLMcAH26vFfvv6UNqRYdPqkd4nwFCNAitdYgQwV411XnRfb --source tz1RaLMsRaFZiApmpSqB2qkkASw8D4YvJVm4 cassonetto.liq --call cassonetto dep '(1,tz1RaLMsRaFZiApmpSqB2qkkASw8D4YvJVm4)'
Main contract Cassonetto
Error: "Assert_failure ./tools/liquidity/liquidToOCaml.ml:131:27"
Backtrace:
Raised at file "src/core/lwt.ml", line 2987, characters 20-29
Called from file "src/unix/lwt_main.ml", line 26, characters 8-18
Called from file "./tools/liquidity/liquidDeploy.ml", line 1422, characters 4-66
Called from file "list.ml", line 100, characters 12-15
Called from file "arg.ml", line 260, characters 8-27
Called from file "arg.ml", line 281, characters 4-31
Called from file "./tools/liquidity/liquidMain.ml", line 669, characters 4-74

**Comment by mebsout** [comment]
Thank you, this is fixed in next by #170.
