### ISSUE TITLE
try-Liquidity example mulitisig.liq does't support transfer to KT1 address. only implicit(tz1) adders

### ISSUE THREAD

**Issue by purplecity** [OCamlPro/liquidity#192]
it is often exist this situation:

transfer xtz between  2 KT1 address. but the multisig.liq does't support this. I try to change this multis .liq file but not succeeded.

problem also in :
https://tezos.stackexchange.com/questions/673/how-to-transaction-from-a-kt1-address-to-another-kt1-address

```
type proposition = {
  destination : address;
  amount : tez;
}

...
      if should_execute (p, storage) then
      (* execute proposition, i.e. transfer tokens *)
        let c_dest = match (Contract.at p.destination : UnitContract.instance option) with
          | None  -> failwith "Invalid contract"
          | Some qr -> qr in
        let op = Contract.call c_dest p.amount () in

```

**Comment by mebsout** [comment]
This is simply a toy example to showcase Liquidity. But if you want transfers to KT1 contracts you can use `UnitContract.instance`. Here is the same contract with this change.

```ocaml
[%%version 0.5]

(* A proposition of transfer to a destination, the address of (unit, unit)
   contract *)
type proposition = {
  destination : UnitContract.instance;
  amount : tez;
}

(* An owner can submit a proposition or remove a previously submitted
   proposition *)
type action = proposition option

type storage = {
  owners : address set;                 (* set of owners *)
  actions : (address, proposition) map; (* map of owner to proposition *)
  owners_length : nat;                  (* total number of owners *)
  min_agree : nat;                      (* minimum number of required
                                           agreements before proposition is
                                           executed *)
}

let%init storage (owners : address set) (min_agree : nat) =
  let owners_length = Set.size owners in
  if min_agree > owners_length then
    Current.failwith "Number of owners must be greater or equal to quorum";
  {
    owners;
    owners_length;
    min_agree;
    actions = Map;
  }

(* fails if the proposition is not a valid one *)
let[@inline] check_proposition p =
  if p.amount > Current.balance () then
    Current.failwith "Balance to low for withdrawal"
  else ()

(* returns true if two proositions are identical *)
let[@inline] equal_props (p1, p2) =
  Contract.address p1.destination = Contract.address p2.destination &&
  p1.amount = p2.amount

(* returns true if a proposition p should be executed immediately *)
let should_execute (p, storage) =
  let nb_agree =
    Map.fold (fun ((_, p'), cpt) ->
        if equal_props (p, p') then cpt + 1p else cpt
      ) storage.actions 0p
  in
  nb_agree >= storage.min_agree

let%entry pay (parameter : unit) storage =
  (* Simple payment, nothing to do *)
  [], storage

let%entry manage (action : action) storage =
  (* Owner wants to perform an action *)
  let owner = Current.source () in
  (* the caller must be an owner*)
  if not (Set.mem owner storage.owners) then
    Current.failwith ("Not an owner", owner);
  (* Don't send money while managing multisig *)
  if Current.amount () <> 0tz then
    Current.failwith "Don't send money while managing multisig";
  (* Register the desired action in the storage *)
  let storage =
    storage.actions <- Map.update owner action storage.actions in
  let do_nothing = [], storage in
  match action with
  | None ->
    (* action is to remove previous proposition: nothing to do *)
      do_nothing
  | Some p ->
    (* The action is new proposition *)
      check_proposition p; (* it must be a valid one *)
      if should_execute (p, storage) then
      (* execute proposition, i.e. transfer tokens *)
        let op = Contract.call p.destination p.amount () in
      (* reset the map of actions *)
        [op], storage.actions <- Map []
      else
        do_nothing
```

**Comment by purplecity** [comment]
yeah but it is just for transfer TO KT1. could change it to support transfer to both tz1 and KT1？ thanks。it is will very helpful

**Comment by purplecity** [comment]
@mebsout hi I just try u wirte .liq   it is error when transfer to KT1 address 
<img width="709" alt="image" src="https://user-images.githubusercontent.com/38914615/53797625-8105b500-3f71-11e9-9951-3b0a75e35b20.png">

**Comment by purplecity** [comment]
can reopen this?

**Comment by mebsout** [comment]
You should use a contract (of type unit) that exists on the blockchain,
like KT1Wgq75N1BcwxXVzsLXQDbGmjKhUceK7JvY for instance on the alphanet.

**Comment by purplecity** [comment]
@mebsout  try u KT1Wgq75N1BcwxXVzsLXQDbGmjKhUceK7JvY this address is ok。but still have 2 question：

1  my KT1 address  KT1DKT2QpnwNnRCzVnYYuwuZuuS2AAajHBC4 is exist on the blockchain(  has transaction and balance not 0 is mean "exist on the blockchain"?). but still failed

2 u address KT1Wgq75N1BcwxXVzsLXQDbGmjKhUceK7JvY has no Michelson  code. if a KT1 has address ,it will be transfer success?

3 can't both transfer to tz1 address

**Comment by mebsout** [comment]
1. KT1DKT2QpnwNnRCzVnYYuwuZuuS2AAajHBC4 is not a unit contract, so you cannot transfer to it using this smart contract. Contract are typed in Tezos, which inherently prevents writing generic code for calling different types of smart contracts.

2. If a KT1 has no code it will be of type UnitContract.instance. If it has code, it must take a unit as parameter for it to be used.

3. Yes, you can. You can make a call with `tz1XEKgRQtqV2XamF9CR7avwNq1V2hPDgNbL` in the destination field for instance. This is also a valid UnitContract.instance literal, in this case it represent the implicit contract associated to this hey hash.

**Comment by purplecity** [comment]
oh. really thanks. it helpful.  but ... the true scene is： transfer tezos between 2 KT1 address which has  Michelson code(because this 2 KT1 address are multisign address. need owners).

so how to write a .liq file do this ?
