### ISSUE TITLE
Wrong link to tzscan instead of zeronet.tzscan

### ISSUE THREAD

**Issue by smondet** [OCamlPro/liquidity#199]
When deploying to zeronet:

![screenshot-20190319-110622](https://user-images.githubusercontent.com/617111/54617089-0f306f80-4a37-11e9-82cd-61ab07faa7b9.png)

the links all point to tzscan.io instead of zeronet.tzscan.io

![screenshot-20190319-110655](https://user-images.githubusercontent.com/617111/54617180-32f3b580-4a37-11e9-85c7-4a7c1d95ecbc.png)

**Comment by mebsout** [comment]
Thanks for the report. The editor now defaults to zeronet when it does not recognize the chain_id which should prevent future breakage as zeronet is reset frequently.
