### ISSUE TITLE
Generation of a ill-typed program

### ISSUE THREAD

**Issue by fab13n** [OCamlPro/liquidity#2]
with commit 439c479c009b2d819a5f2674f4a1993caba5257d

This contract:
```
let contract
  	(amount: tez)
	(parameter: int)
	(storage: unit)
	(return: int) =
  parameter + (1:int), ()
```

compiles fine:
```
$ liquidity.asm add1.liq
File "add1.liq.tz" generated
Typecheck with:
  tezos-client typecheck program add1.liq.tz
```

But generates ill-typed Michelson:

```
$ tezos-client typecheck program add1.liq.tz
Ill typed contract:
  storage unit ;
  parameter int ;
  return int ;
  code
    { /* [ pair int unit ] */
      DUP ;
      /* [ pair int unit : pair int unit ] */
      DIP { /* [ pair int unit ] */
            CDR
            /* [ unit ] */ } ;
      /* [ pair int unit : unit ] */
      DIP { /* [ unit ] */
            DROP
            /* [] */ } ;
      /* [ pair int unit ] */
      CAR ;
      CDR /* 1 */ ;
      PUSH unit Unit ;
      PUSH int 1 ;
      { DIP { DIP { DUP } ;
              SWAP } ;
        SWAP }
      { DIP { DIP { DIP { DROP } } } }
      ADD ;
      PAIR }
At mark /* 1 */, wrong stack type for instruction CDR: [ int ].
Fatal error: ill-typed program
```
That's actually the case with every program I've tried to compile, I just gave the simplest example I had.

I tried to run you suit test:

* there's a path hard-coded in `check.sh` line 8;
* all of them fail as well.

tezos-client is compiled on Ubuntu 16.04 from commit tezos/tezos@49fea59a19f7519f317d74fb9bf5543d37a26307, but it doesn't seem to be the issue, when looking at generated Michelson code there's actually a type error.

**Comment by lefessan** [comment]
This was a problem with the removal of the "amount" in the initial stack. It is fixed in the current version.
