### ISSUE TITLE
<valid private key> is not a valid private key

### ISSUE THREAD

**Issue by maht0rz** [OCamlPro/liquidity#205]
When i try to deploy a contract directly, without forging an operation locally, I get an error saying that the `--private-key` i'm using is not valid.

```
Failure: edsk3gUfUPyBSfrS9CCgmCiQsTCHGkviBDusMxDJstFtojtc1zcpsh is not a valid private key
```

This feature is described in the docs here: http://www.liquidity-lang.org/doc/usage/index.html#deploying-a-contract-directly-unsafe

I've tried with several combinations of private keys / sources with no luck.

**Comment by mebsout** [comment]
Fixed in #190.
