### ISSUE TITLE
Init storage construction issue when using Contract.create

### ISSUE THREAD

**Issue by catsigma** [OCamlPro/liquidity#206]
If `a.liq` has a storage type like `type storage = {x: address, y: address}`

When using `Contract.create` to create an `a`-type contract in `b.liq`, I cannot construct the init storage for contract `a`.

It will show the error: `Type error:  unbound record label "x"`

version: 1.03

**Comment by mebsout** [comment]
You should qualify the records field in other modules (like in OCaml), _i.e._ you should construct your record with `let s = { A.x = .... ; A.y = ... } in ...`.  If you want to access the field `x` of `s` in module B, you can use `s.A.x`.
