### ISSUE TITLE
build-deps are missing the ocaml-migrate-parsetree package

### ISSUE THREAD

**Issue by ejgallego** [OCamlPro/liquidity#221]
On a fresh install from `next`, `make` will fail with:
```
...
Warning: missing package "ocplib-liquidity-parser":
  Disabling package "ocplib-liquidity-base".
    (from "/home/egallego/b/liquidity/tools/liquidity/build.ocp2")
Warning: missing package "ocaml-migrate-parsetree":
  Disabling package "ocplib-liquidity-parser".
```
this is due to `ocaml-migrate-parsetree` missing from build-deps.

**Comment by andy-morris** [comment]
`camlp4` and `ctypes-foreign` are also missing.

**Comment by grouville** [comment]
Same error for me, as well as this error : `make: *** [_obuild/liquidity/liquidity.asm] Error 2`error

Have you found a way to install it ?

**Comment by andy-morris** [comment]
I just installed the missing dependencies before running make, with `opam install ocaml-migrate-parsetree camlp4 ctypes-foreign`.

**Comment by mebsout** [comment]
Thanks for the report. There is no need for `camlp4` and `ctypes-foreign` though.
