### ISSUE TITLE
key_hash to address type coercion do not work

### ISSUE THREAD

**Issue by akettal** [OCamlPro/liquidity#228]
Hi guys.

Although the documentation allows type coercion from `key_hash` to `key` type, it does not work.

The following example doesn't compile and show this error (at line 7):
> Unexpected type in annotated expression. Expected type : address, actual type : key hash

```ocaml
type storage = address option

let%init storage = None

let%entry main (key : key) _ = 
  let key_hash = Crypto.hash_key key in
  let address = ( key_hash : address ) 
  in ( [], Some address )
```

**Comment by mebsout** [comment]
Coercion only work for _constants_. We'll try to make this more explicit in the documentation.
If you want to get a corresponding address from a key hash you can use:
```ocaml
let address = Contract.address (Account.default key_hash) in ...
```
