### ISSUE TITLE
make: Error: missing source file "./libs/dune-network-lib/../../dune-network/vendors/ocplib-json-typed/src/json_repr.ml" for package "ocplib-json-typed"

### ISSUE THREAD

**Issue by atorrente75** [OCamlPro/liquidity#231]
i'm trying to install liquidity using this instructions:
[http://www.liquidity-lang.org/doc/installation/index.html](url)

but i get this error:

`make

ocp-build build liquidity

Compiler: ocaml 4.06.1

Error: missing source file "./libs/dune-network-lib/../../dune-network/vendors/ocplib-json-typed/src/json_repr.ml" for package "ocplib-json-typed"
  (You may need to  manually disable compilation of this package
  with 'enabled = false')
Makefile:30: recipe for target '_obuild/liquidity/liquidity.asm' failed
make: *** [_obuild/liquidity/liquidity.asm] Error 2
`

**Comment by mebsout** [comment]
You should use `make clone-dune-network` instead of `make clone-tezos` before compiling. This is a recent change, and the documentation was updated accordingly. Can you let us know if that solves your issue?

**Comment by atorrente75** [comment]
I apologize for the (very) late reply, yes, the suggestion you gave me solved the problem, thanks
