### ISSUE TITLE
Pin the version of ocaml-migrate-parsetree

### ISSUE THREAD

**Issue by annenkov** [OCamlPro/liquidity#254]
Currently, if one follows the instructions here https://www.liquidity-lang.org/doc/installation/index.html, the build fails:

```
- stderr for ...quidity-parser/reason_syntax_util.cmi --
File "./tools/liquidity/reason/reason_syntax_util.mli", line 41, characters 2-20:
Error: Unbound module Ast_404.Location
```

This is due to the version of `ocaml-migrate-parsetree` which is not restricted, so the latest version is installed (2.0.0). It seems this version is incompatible with the Liquidity compiler, while it builds fine with ocaml-migrate-parsetree.1.5.0.

**Comment by mebsout** [comment]
Thanks for catching this :) I've added a constrain on `ocaml-migrate-parsetree` which should fix the issue.
