### ISSUE TITLE
[next branch] Bad stack length.

### ISSUE THREAD

**Issue by catsigma** [OCamlPro/liquidity#36]
https://github.com/catsigma/bettingwin/blob/master/contracts/bet/bet_main.liq

This file is compiled successfully in liquidity, but the compiled contract cannot pass the typecheck of alphanet.

It displays error
```
...........
...........
...........
)) ].
Bad stack length.
Fatal error: ill-typed program
```

**Comment by mebsout** [comment]
Thanks for reporting this issue. This should now be fixed in branch `next`.
