### ISSUE TITLE
docs have wrong type for Account.default argument

### ISSUE THREAD

**Issue by something3** [OCamlPro/liquidity#65]
DEFAULT_ACCOUNT : Account.default key. Returns the default contract (of type (unit,unit) contract) associated with a key.

Should be:

DEFAULT_ACCOUNT : Account.default **key_hash**.

It seems that the instruction HASH_KEY which makes a key_hash from key doesn't exist in Liquidity. Is there another way to do it?

**Comment by mebsout** [comment]
The docs were updated to reflect this. Also you can use `Crypto.hash_key` which is the equivalent of Michelson's `HASH_KEY`.
Thanks for noticing that.
