### ISSUE TITLE
xor doesnt seem to work

### ISSUE THREAD

**Issue by something3** [OCamlPro/liquidity#66]
Trying to use the xor operator gives me a "unbound variable xor". If I replace it with other operators like >> && or ||, it works.

Is there a different notation I should use?

**Comment by mebsout** [comment]
It used to be (mistakenly) parsed as a prefix operator, but is now infix so you should be able to write `a xor b`. The version of Liquidity with the fix (0.16) is in branch `next` at the moment.
The version on http://liquidity-lang.org/edit is also fixed. Thanks for catching that.
