### ISSUE TITLE
change Michelson data literals to zeronet.

### ISSUE THREAD

**Issue by catsigma** [OCamlPro/liquidity#70]
The data literals in zeronet has been changed to this https://gitlab.com/tezos/tezos/blob/master/src/bin_client/test/test_contracts.sh

Please update it in the next branch, thanks.

**Comment by catsigma** [comment]
@mebsout 
Sorry for the mention, in case no one saw this issue.

**Comment by mebsout** [comment]
There is now a new branch `zeronet` which should work with the current Tezos zeronet. The online editor that works with the zeronet is accessible at http://www.liquidity-lang.org/zeronet/ .
Let us know if you find issues with the new changes.

**Comment by catsigma** [comment]
@mebsout Thanks, I'll keep looking into it.
