### ISSUE TITLE
How to Activate wallet in Localhost and Zeronet test network

### ISSUE THREAD

**Issue by calmesriram** [OCamlPro/liquidity#88]
Hello sir,

1.    As i was gone on Liquidity online editor in that there is a settings and i was chosen zeronet. it was opened some option below the option there is a link to download json file. i was downloaded browsed by option and i chosen file .its shows Activating but not activating in online editor 

2. how do i deploy other contracts in testnetwork of (Zeronet). when i code and compile it compiler    compiles and converted into Michelson languge ok. and its runs but i couldn't deploy in network

**Comment by mebsout** [comment]
We were running an old version of the zeronet node where no one was baking anymore. We have update it now, so you should now be able to activate faucet wallets and deploy contracts on it.
