### ISSUE TITLE
Restore alphanet node and deployment

### ISSUE THREAD

**Issue by ktorn** [OCamlPro/liquidity#89]
Even though the main [site](http://www.liquidity-lang.org/) still lists "TRY ON ALPHANET" and "TRY ON ZERONET", seems like both link to "betanet" and under Settings the alphanet node was removed.

Is it possible to re-enable the alphanet node so that we can deploy to alphanet from this tool?

**Comment by mebsout** [comment]
We were running a previous version of the zeronet where no one was baking anymore. We have updated our node so you can use that now to test contracts. Tezos has not released an alphanet apart from the one from 3 month ago which is not compatible with either the latest version of Liquidity or Michelson.
We'll add back the alphanet node when they update it, in the meantime you can use the zeronet node (faucet wallets also work on this one).
