### ISSUE TITLE
Tezos node

### ISSUE THREAD

**Issue by desingraja** [OCamlPro/liquidity#91]
I'm running the tezos node more than one day but it not synchronize with the testnet

**Comment by mebsout** [comment]
You need to run a version of Tezos that uses the same network id for it to synchronize. For instance, use the branch https://gitlab.com/tezos/tezos/tree/betanet for a node that can run on the betanet.
Please open issues regarding Tezos on the Tezos gitlab: https://gitlab.com/tezos/tezos/issues
