### ISSUE TITLE
liquidity.asm: not found

### ISSUE THREAD

**Issue by munakaya** [OCamlPro/liquidity#94]
Build Successful in 3.74s. 51 jobs (parallelism 1.7x), 101 files generated.
Build is Fine.
But liquidity-mini.asm: not found

test@test-VirtualBox:~/tmp/master/liquidity$ ./check.sh
[check.sh] test = 
./_obuild/liquidity/liquidity.asm --verbose tests/.liq
./check.sh: 17: ./check.sh: ./_obuild/liquidity/liquidity.asm: not found
1+MKMFT
04:09

**Comment by lefessan** [comment]
There was probably a problem with the dependencies. Check with `ocp-build --project-warnings` to see which package is missing.
